### ISSUE TITLE
logs does not show in the Unity Console log

### ISSUE THREAD

**Issue by sk-ericso** [draxov/UnityLog4Net#1]
Nothing shows in Unity Console log.  I am using Unity version 5.0.1p3.  I don't have app.config or log4net.xml in the project.  And no instruction on how to setup. :(

**Comment by draxov** [comment]
Hey, I've commited a new version now with an example log4net.xml in it and a Unity Appender, please try the latest, though I have changed the folder structure so make sure you delete previous version, sorry for not keeping this up to date, but it was kind of a share while it was working thing
